### ISSUE TITLE
Typo on Normal/Basic Skill Description in English Language - Chihoro

### ISSUE THREAD

**Issue by jackatrades** [lonqie/SchaleDB#13]
Character ID: 20013

Through the Backdoor
"Every 30s, decreases the <d:ATK> of the enemy with the highest ATK by <?1> for 30s."

The debuff length is 23 seconds, not 30. (I believe the Mirahaze wiki also has it listed at the wrong duration if this was where it was pulled from)

JP language has the correct length defined:
"30秒毎に、攻撃力が最も高い敵1人の<d:ATK>を<?1>減少（23秒間）"

**Comment by lonqie** [comment]
Fixed in 8d994ecb559b46e76d598693c7b12c4309bce02d
