### ISSUE TITLE
Typo on Gear Normal+/Basic+ Skill Description in English Language - Hare

### ISSUE THREAD

**Issue by jackatrades** [lonqie/SchaleDB#14]
Character ID: 23003

Sabotage: Plan A+
"Every 30s, decreases the <d:HealEffectiveness> of one enemy by <?1> for 15s."

The debuff length is upgraded from 15 seconds to 25 seconds.

JP language has the correct length defined:
"30秒毎に、敵1人の<d:HealEffectiveness>を<?1>減少（25秒間）"

**Comment by lonqie** [comment]
Fixed in 8d994ecb559b46e76d598693c7b12c4309bce02d
