### ISSUE TITLE
List individual probability of crafting nodes appearing

### ISSUE THREAD

**Issue by czhangsze** [lonqie/SchaleDB#15]
lonqie,

 Hi, my name is Samuel. I'm bad in English. Thanks for making SchaleDB, It's very helpful. I would like to comment on this website. I want to know the the probability of each node. For example, I want to know how many percent I can get “Wealth” in 3rd node,

**Comment by lonqie** [comment]
By this do you mean the % chance of each node appearing?

**Comment by czhangsze** [comment]
> 你的意思是每個節點出現的百分比嗎？

Yes

**Comment by czhangsze** [comment]
> 你的意思是每個節點出現的百分比嗎？

![螢幕擷取畫面 2022-10-03 194741](https://user-images.githubusercontent.com/114921786/193570034-f6791851-5795-49a7-b078-6d18391e0d10.png)
For example , I want to know % chance of “Wealth” in 3rd node?

**Comment by lonqie** [comment]
Cool, that should be possible.

I believe the probability is equal to the `Weight` of each node / sum of `Weight` for every node in the group but I will need to verify with the official probability sheet released by nexon.

**Comment by lonqie** [comment]
This has now been added as of 84cd74630f960b23705be9499818f771b3200ebd. To toggle display of this information on/off you will need to click the following button on the Crafting page.

![image](https://user-images.githubusercontent.com/95139223/198996309-1916029e-6fa8-436f-8453-2935f412f609.png)
