### ISSUE TITLE
Crit DMG RES Cap

### ISSUE THREAD

**Issue by NintendoAris** [lonqie/SchaleDB#17]
Recent update made it to be capped at 80%, but in the game it's only capped at damage calculation.
Buff/Debuff is calculated based on its actual stat, 10000.
So the dmg calculation feature is a bit wrong right now.
-30% crit res on binah should result in 100%*0.7 = 70%, not 80%*0.7 = 56%.

**Comment by lonqie** [comment]
The calculation is correct, stat limits are applied to the value before buff/debuff % and not just at the point of damage calculation.

So for example, S.Izuna Basic Lv10 applied to Shiro Insane: the Crit DMG RES debuff (-38.97%) is applied to the _already limited value_ (8,000) resulting in a final Crit DMG RES of 4882 (48.82%)

Source: https://twitter.com/SLC_Sil/status/1577890664511336450

**Comment by NintendoAris** [comment]
I'm so sorry, I think I forgot calculating stability debuff when I tried with binah.
