### ISSUE TITLE
0.1% difference in stat details tab.

### ISSUE THREAD

**Issue by NintendoAris** [lonqie/SchaleDB#18]
Sometimes a skill percentage is 0.1% higher in calculation feature, for example the buff percentage of Akari's basic skill, or inherit percentage of Iroha EX.
It's meaningless difference, but I'm curious where the 0.1% difference comes from.

**Comment by lonqie** [comment]
The difference is due to raw values being used in calculations.
In game skill descriptions typically round down to the closest 1% or 0.1%, so you will occasionally see some discrepancies between the two.
