### ISSUE TITLE
Wakamo EX DMG Cap calculates DMG Res

### ISSUE THREAD

**Issue by NintendoAris** [lonqie/SchaleDB#20]
I mean "DMG Res" by "Incoming DMG Res".
https://twitter.com/SLC_Sil/status/1488876021927452677
The explosion of Wakamo's EX bypasses DMG Res stats.
I also checked today on shirokuro that the explosion damage is exactly same on kuro, with and without DMG Res debuff.

**Comment by lonqie** [comment]
This has been corrected in 5a02d49bead3b91394daa3563f19221b4d10c5f0
