### ISSUE TITLE
Students should not be imported from Justin's planner when set as not Obtained

### ISSUE THREAD

**Issue by Z-95** [lonqie/SchaleDB#25]
You can use Justin's planner to plan for future gained students by unchecking their Obtained checkbox in their eleph section which lets you plan out future material needs and for hard mode farmable students it will add the required unlock elephs to their needed total.

However when importing the JSON dump from Justin's planner every student existing in the JSON is automatically set as Owned. Instead, the import function could check the eleph.unlocked boolean in Justin's export JSON and only set as Owned if it is true.

**Comment by lonqie** [comment]
Fixed as of 3527f1e03ba70eace07a356326e71d5bb76b33b7
