### ISSUE TITLE
Question: Licensing

### ISSUE THREAD

**Issue by timescam** [lonqie/SchaleDB#27]
Hi, thanks for making SchaleDB! It's very useful.

Since there are no license or readme in this repo, I would like to know if it is suitable for me to use the curated data ([students.json](https://github.com/lonqie/SchaleDB/raw/main/data/en/students.json) for example) in this repo for my personal projects.

**Comment by sctop** [comment]
Issue #23 seemed to have already answered this question, yet I'm also concerned about the data license.
I am planning to use a part of SchaleDB data recently as well (mostly images), so I guess I would just comment here to avoid opening up another same issue.

**Comment by lonqie** [comment]
Hi, yes as answered before I don't have a problem with game data being reused for other projects so long as:

- You acknowledge that the format is subject to changes without notice and data being added and/or removed
- Translations are not used without permission of whoever contributed them
