### ISSUE TITLE
Typo on Normal/Basic Skill Description in English Language - Chinatsu (Hot Spring)

### ISSUE THREAD

**Issue by jackatrades** [lonqie/SchaleDB#3]
Character ID: 10030

**Reinforced Combat Enhancement**
"Every 25s, increases the <b:AttackSpeed> of one ally by <?1> for 30s."

The buff length is 20 seconds, not 30.

JP language has the correct length defined:
"25秒毎に、自身を除く味方1人の<b:AttackSpeed>を<?1>増加（20秒間）"

**Comment by lonqie** [comment]
Thanks, fixed in d69526dbfd214af04f18d4f0fffefb60ad44f930
