### ISSUE TITLE
Suggestion of show furniture craftable flag at item page

### ISSUE THREAD

**Issue by OkazakiNaoki** [lonqie/SchaleDB#31]
I don't know if it is true when the furniture that show up at craft node means it could be crafted.
If the case is true then which means craftable flag could be done by find target furniture at craft node data right?

By the way, thanks for the site. It's beautiful.

**Comment by lonqie** [comment]
Thanks for the suggestion.
So I understand the use case, are you suggesting for a filter to be able to find craftable furniture more easily or you want to see which craft nodes can drop a specific furniture?
I think both are useful to features to add

**Comment by OkazakiNaoki** [comment]
Find craftable furniture. Since some of them are event limit. (might unlock later though)
If there's a flag of craftable information inside each of furniture item information then we can be more confident to ignore some of non-event-limited furniture inside event store.

Thanks again. For the reply.

**Comment by lonqie** [comment]
It is now possible to see crafting nodes and consumables that drop an item or furniture on the item's page. It is also possible to filter the view to only show craftable items. This should make it easy to identify if a furniture is limited or not
