### ISSUE TITLE
What license those this project have?

### ISSUE THREAD

**Issue by Fyzbyt** [lonqie/SchaleDB#32]
I want to make an API and would want to use the files to store in a database.

**Comment by lonqie** [comment]
Hi, please see my answers to #23 and #27,

You are free to use the data however if you are planning to regularly import the data, be aware the format is subject to change with no notice provided.

The main exception would be translations that do not originate from the game as this is the work of other contributors. For these you will need permission from the translator (please contact me via discord @lonqie to discuss if it's the case)
