### ISSUE TITLE
found a bug

### ISSUE THREAD

**Issue by Qiantong1226** [lonqie/SchaleDB#33]
(This message is machine translated)
The duration of Kotama's Basic Skill is 20 seconds, but it is wrongly displayed as 30 seconds in the Simplified Chinese version。please fix it
![bug](https://github.com/lonqie/SchaleDB/assets/144385627/ddedeff5-66df-4f8f-8fc5-c4a99c96e670)

**Comment by lonqie** [comment]
Thank you for bringing this to my attention, the mistake has been corrected
