### ISSUE TITLE
Typo on Weapon Passive Skill Description in English Language - Nonomi (Swimsuit)

### ISSUE THREAD

**Issue by jackatrades** [lonqie/SchaleDB#7]
Character ID: 10044

Passive:
"Desc": "Every 40s, increases the **<b:AttackSpeed>** of allies in a circular area by <?1> for 30s.",

Weapon Passive:
"Desc": "Increases <b:Penetration> by <?1> and **<b:ATK>** by <?2>.",

<b:ATK> should be <b:AttackSpeed> instead

**Comment by lonqie** [comment]
Thanks (again!) Fixed in 042b9271dd758a6a0b931928ac01c1462f813de1
