### ISSUE TITLE
jp AP description is wrong

### ISSUE THREAD

**Issue by edwardez** [lonqie/SchaleDB#9]
<img width="1306" alt="image" src="https://user-images.githubusercontent.com/11089470/184517916-bc0e061b-b937-4ec3-9298-c055ae61d963.png">
Currently it is "大人のカードで購入できる神秘的な宝石。様々な商品を購入・取引できる。"(this is the description for pyroxenes) however it should be "先生の体力の数値。様々な行動をするたびに消耗する。"

Not sure if this is the official translation, I [got](https://www.google.com/search?q=%22Sensei%27s+vigor+level%22) it from a [random](https://wiki.biligame.com/m2cn/LocalizeEtcExcelTable?biliLogin=1&biliLogin=1) website but I am able to read Japanese and can confirm this is accruate.
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/11089470/184517967-76ba03b8-7cda-4e56-887c-327cfe709127.png">

**Comment by lonqie** [comment]
Yeah that translation looks correct, `先生の体力の数値。様々な行動をするたびに消耗する。`
Currencies is from a part of the data that hasn't been put into the script that generates the translations automatically, so this was a copy/paste mistake from my old ways of doing things 🙂 
Gonna split this out into currency.json and have it be automatically generated like the rest. It's also missing the Thai translations atm too.

**Comment by lonqie** [comment]
Fixed as of 8d27760c2a310552a19eab428a89a3a275b00920
