### ISSUE TITLE
The summon data of Ajitani Hifumi is wrong

### ISSUE THREAD

**Issue by saya1024** [lonqie/SchaleDB#90]
In the new version of the website, after adjusting the equipment, the data of the Peloro doll has not changed.
![屏幕截图 2024-09-12 230214](https://github.com/user-attachments/assets/4b64aaa6-f305-4449-8940-1a8ede4743ef)
System: Win10
Browser:  edge ver128.0.2739.67
SchaleDB version: 1.1.0

**Comment by saya1024** [comment]
Utaha, Nodoka (Hot Spring), Mimori (Swimsuit), Kirino (Swimsuit), Hoshino (Battle), looks like a similar problem. There is something wrong with their summon data

**Comment by saya1024** [comment]
I think you'd better check the data of all summons.

**Comment by lonqie** [comment]
There is nothing wrong with the data of the summons, the problem is you haven't enabled the inheritance skill. To do that you need to open the 'Skills' window and make sure it is switched to ON

![image](https://github.com/user-attachments/assets/8d0ea1b8-98d0-4bbf-8b63-6247d999ea8e)
